name = "VerifyMacros"
uuid = "af467e45-a3cd-48cc-969b-d17b4696c409"
version = "1.0.0-DEV"
authors = ["Joris Pinkse <pinkse@gmail.com> and contributors"]

[deps]
StyledStrings = "f489334b-da3d-4c2e-b8f0-e476e12c162b"

[compat]
StyledStrings = "1.11.0"
julia = "1.12"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
