name = "VerifyMacros"
uuid = "af467e45-a3cd-48cc-969b-d17b4696c409"
version = "0.1.0"
authors = ["Joris Pinkse <pinkse@gmail.com> and contributors"]

[deps]
PrecompileTools = "aea7be01-6a6a-4083-8856-8a6e6704d82a"
StyledStrings = "f489334b-da3d-4c2e-b8f0-e476e12c162b"

[compat]
Aqua = "0.8.14"
PrecompileTools = "1.3.3"
StyledStrings = "1.11.0"
Test = "1"
julia = "1.12"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Aqua"]
