[deps]
ArgCheck = "dce04be8-c92d-5529-be00-80e4d2c0e197"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
VerifyMacros = "af467e45-a3cd-48cc-969b-d17b4696c409"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
